-- WP2 hash parity: Snowflake's CANONICAL_HASH must reproduce contracts/vectors/canonical_hash.json.
-- Generated by `uv run python -m blueberrychain.sqlgen`; tests/test_sqlgen.py fails if it drifts.

-- test: CANONICAL_HASH reproduces every cross-language vector
SELECT v.column1 AS input_json, v.column2 AS expected_sha256,
       BBC_OS.LEDGER.CANONICAL_HASH(PARSE_JSON(v.column1)) AS actual_sha256
FROM VALUES
  ('{"case_id": "CASE-00000017", "nrv_usd": 45301, "lots": ["L-A"], "ok": true}', 'cd443761ea144ab9d5ebda8ff910af7fa1d240e73096fd2f71cb8fde6d8b335b'),
  ('{"b": [1, {"d": null, "c": true}], "a": "caf\\u00e9"}', '7ef766dc012950a1967b8047d977b2935a815934653f66e64d9cd141ac01c3c4'),
  ('{"price": 11.2, "kg": 4200.0, "tiny": 1e-07}', '4fcb1587fbca240c450bc4634d0eda4a88fed5b771ddddd0a3a1b93a59942ade') v
WHERE BBC_OS.LEDGER.CANONICAL_HASH(PARSE_JSON(v.column1)) <> v.column2;
