-- WP3 physics parity: the SQL functions must reproduce python bbc_engine.physics.
-- Generated by `uv run python -m blueberrychain.sqlgen`; tests/test_sqlgen.py fails if it drifts.

-- test: OPS.SHELF_LIFE_RATE equals bbc_engine.physics.rate
SELECT v.column1 AS temp_c, v.column4 AS expected,
       BBC_OS.OPS.SHELF_LIFE_RATE(v.column1, v.column2, v.column3) AS actual
FROM VALUES
  (-1.0, 0.0, 3.0, 0.8959584598407622),
  (0.0, 0.0, 3.0, 1.0),
  (0.5, 0.0, 3.0, 1.056467308549538),
  (1.8, 0.0, 3.0, 1.2186579496196162),
  (2.0, 0.0, 3.0, 1.2457309396155174),
  (4.6, 0.0, 3.0, 1.6575848822667927),
  (10.0, 0.0, 3.0, 3.0),
  (24.5, 0.0, 3.0, 14.75526705082986),
  (-1.0, 0.0, 3.2, 0.8901946956877225),
  (0.0, 0.0, 3.2, 1.0),
  (0.5, 0.0, 3.2, 1.0598819568815),
  (1.8, 0.0, 3.2, 1.2328975685665908),
  (2.0, 0.0, 3.2, 1.2619146889603865),
  (4.6, 0.0, 3.2, 1.7075325453417842),
  (10.0, 0.0, 3.2, 3.2),
  (24.5, 0.0, 3.2, 17.282933021687725),
  (11.0, 1.0, 2.0, 2.0),
  (-5.0, 0.0, 3.0, 0.5773502691896257) v
WHERE ABS(BBC_OS.OPS.SHELF_LIFE_RATE(v.column1, v.column2, v.column3) - v.column4)
      > 1e-12 * GREATEST(1, ABS(v.column4));

-- test: OPS.PROJECT_SHELF_LIFE_DAYS equals bbc_engine.physics.project_shelf_life_days
SELECT v.column1 AS remaining_h, v.column6 AS expected,
       BBC_OS.OPS.PROJECT_SHELF_LIFE_DAYS(v.column1, v.column2, v.column3, v.column4, v.column5) AS actual
FROM VALUES
  (240.0, 15.0, 0.5, 0.0, 3.0, 9.33970793215654),
  (300.0, 6.0, 4.0, 0.0, 3.2, 12.101892829446504),
  (48.0, 30.0, 12.0, 0.0, 3.0, -2.6714910235581897) v
WHERE ABS(BBC_OS.OPS.PROJECT_SHELF_LIFE_DAYS(v.column1, v.column2, v.column3, v.column4, v.column5) - v.column6)
      > 1e-12 * GREATEST(1, ABS(v.column6));
