"""Generated SQL test files. Regenerate with `uv run python -m blueberrychain.sqlgen`."""

from __future__ import annotations

import json
from pathlib import Path

from bbc_engine import physics

from blueberrychain import semantic

ROOT = Path(__file__).resolve().parents[4]
VECTORS = ROOT / "contracts" / "vectors" / "canonical_hash.json"
HASH_PARITY = ROOT / "snowflake" / "tests" / "02_hash_parity.sql"
PHYSICS_PARITY = ROOT / "snowflake" / "tests" / "03_physics_parity.sql"
SEMANTIC_VIEW = ROOT / "snowflake" / "modules" / "70_semantic_view.sql"

# (temp_c, tref_c, q10): the product range plus extremes and a non-zero reference temperature.
RATE_CASES = [(t, 0.0, q) for q in (3.0, 3.2) for t in (-1.0, 0.0, 0.5, 1.8, 2.0, 4.6, 10.0, 24.5)]
RATE_CASES += [(11.0, 1.0, 2.0), (-5.0, 0.0, 3.0)]
# (remaining_h, hours_ahead, temp_c, tref_c, q10)
PROJECTION_CASES = [
    (240.0, 15.0, 0.5, 0.0, 3.0),
    (300.0, 6.0, 4.0, 0.0, 3.2),
    (48.0, 30.0, 12.0, 0.0, 3.0),
]
HEADER = (
    "-- Generated by `uv run python -m blueberrychain.sqlgen`; tests/test_sqlgen.py fails if "
    "it drifts.\n"
)


def _literal(text: str) -> str:
    """Single-quoted Snowflake literal (backslash is an escape character there)."""
    return "'" + text.replace("\\", "\\\\").replace("'", "''") + "'"


def hash_parity_sql(vectors_path: Path = VECTORS) -> str:
    vectors = json.loads(vectors_path.read_text(encoding="utf-8"))["vectors"]
    rows = ",\n  ".join(
        f"({_literal(json.dumps(v['input'], ensure_ascii=True))}, '{v['sha256']}')" for v in vectors
    )
    return (
        "-- WP2 hash parity: Snowflake's CANONICAL_HASH must reproduce "
        "contracts/vectors/canonical_hash.json.\n" + HEADER + "\n"
        "-- test: CANONICAL_HASH reproduces every cross-language vector\n"
        "SELECT v.column1 AS input_json, v.column2 AS expected_sha256,\n"
        "       BBC_OS.LEDGER.CANONICAL_HASH(PARSE_JSON(v.column1)) AS actual_sha256\n"
        "FROM VALUES\n"
        f"  {rows} v\n"
        "WHERE BBC_OS.LEDGER.CANONICAL_HASH(PARSE_JSON(v.column1)) <> v.column2;\n"
    )


def physics_parity_sql() -> str:
    rates = ",\n  ".join(
        f"({t!r}, {tref!r}, {q!r}, {physics.rate(t, tref, q)!r})" for t, tref, q in RATE_CASES
    )
    projections = ",\n  ".join(
        f"({r!r}, {h!r}, {t!r}, {tref!r}, {q!r}, "
        f"{physics.project_shelf_life_days(r, h, t, tref, q)!r})"
        for r, h, t, tref, q in PROJECTION_CASES
    )
    project = (
        "BBC_OS.OPS.PROJECT_SHELF_LIFE_DAYS(v.column1, v.column2, v.column3, v.column4, v.column5)"
    )
    return (
        "-- WP3 physics parity: the SQL functions must reproduce python bbc_engine.physics.\n"
        + HEADER
        + "\n"
        "-- test: OPS.SHELF_LIFE_RATE equals bbc_engine.physics.rate\n"
        "SELECT v.column1 AS temp_c, v.column4 AS expected,\n"
        "       BBC_OS.OPS.SHELF_LIFE_RATE(v.column1, v.column2, v.column3) AS actual\n"
        "FROM VALUES\n"
        f"  {rates} v\n"
        "WHERE ABS(BBC_OS.OPS.SHELF_LIFE_RATE(v.column1, v.column2, v.column3) - v.column4)\n"
        "      > 1e-12 * GREATEST(1, ABS(v.column4));\n"
        "\n"
        "-- test: OPS.PROJECT_SHELF_LIFE_DAYS equals bbc_engine.physics.project_shelf_life_days\n"
        f"SELECT v.column1 AS remaining_h, v.column6 AS expected,\n       {project} AS actual\n"
        "FROM VALUES\n"
        f"  {projections} v\n"
        f"WHERE ABS({project} - v.column6)\n"
        "      > 1e-12 * GREATEST(1, ABS(v.column6));\n"
    )


def semantic_view_sql() -> str:
    return semantic.render_sql(semantic.load_model())


GENERATED = {
    HASH_PARITY: hash_parity_sql,
    PHYSICS_PARITY: physics_parity_sql,
    SEMANTIC_VIEW: semantic_view_sql,
}


if __name__ == "__main__":
    for path, render in GENERATED.items():
        path.write_text(render(), encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
