"""Generated SQL test files. Regenerate with `uv run python -m blueberrychain.sqlgen`."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
VECTORS = ROOT / "contracts" / "vectors" / "canonical_hash.json"
HASH_PARITY = ROOT / "snowflake" / "tests" / "02_hash_parity.sql"


def _literal(text: str) -> str:
    """Single-quoted Snowflake literal (backslash is an escape character there)."""
    return "'" + text.replace("\\", "\\\\").replace("'", "''") + "'"


def hash_parity_sql(vectors_path: Path = VECTORS) -> str:
    vectors = json.loads(vectors_path.read_text(encoding="utf-8"))["vectors"]
    rows = ",\n  ".join(
        f"({_literal(json.dumps(v['input'], ensure_ascii=True))}, '{v['sha256']}')" for v in vectors
    )
    return (
        "-- WP2 hash parity: Snowflake's CANONICAL_HASH must reproduce "
        "contracts/vectors/canonical_hash.json.\n"
        "-- Generated by `uv run python -m blueberrychain.sqlgen`; tests/test_sqlgen.py fails if "
        "it drifts.\n"
        "\n"
        "-- test: CANONICAL_HASH reproduces every cross-language vector\n"
        "SELECT v.column1 AS input_json, v.column2 AS expected_sha256,\n"
        "       BBC_OS.LEDGER.CANONICAL_HASH(PARSE_JSON(v.column1)) AS actual_sha256\n"
        "FROM VALUES\n"
        f"  {rows} v\n"
        "WHERE BBC_OS.LEDGER.CANONICAL_HASH(PARSE_JSON(v.column1)) <> v.column2;\n"
    )


if __name__ == "__main__":
    HASH_PARITY.write_text(hash_parity_sql(), encoding="utf-8", newline="\n")
    print(f"wrote {HASH_PARITY.relative_to(ROOT)}")
