-- =====================================================================
-- BlueberryChain OS - 99 Reset Demo State
--
-- Returns the environment to its pinned pre-demo state without
-- reloading seed data. Run this before each demo run.
--
-- It clears everything the agent tools write, and restores the two
-- pinned scenarios:
--   Demo 1: Ranch 14 Block 7 lot AVAILABLE with its 3.8 h excursion
--   Demo 2: yesterday's Tracy DC arrivals uninvoiced
-- =====================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE BLUEBERRY_CHAIN;
USE WAREHOUSE BBC_WH;

-- Audit trail
TRUNCATE TABLE BLUEBERRY_CHAIN.AUDIT.DECISION_LOG;
TRUNCATE TABLE BLUEBERRY_CHAIN.AUDIT.APPROVAL_QUEUE;
TRUNCATE TABLE BLUEBERRY_CHAIN.AUDIT.NOTIFICATIONS;

-- Agent-created operational records
TRUNCATE TABLE BLUEBERRY_CHAIN.RAW.PROCUREMENT_POS;
TRUNCATE TABLE BLUEBERRY_CHAIN.RAW.HARVEST_REQUESTS;

-- Agent-created finance records (seeded history is preserved)
DELETE FROM BLUEBERRY_CHAIN.RAW.INVOICES
 WHERE INVOICE_ID LIKE 'INV-%-0%' AND LENGTH(INVOICE_ID) = 18;
DELETE FROM BLUEBERRY_CHAIN.RAW.GROWER_SETTLEMENTS
 WHERE SETTLEMENT_ID LIKE 'STL-%-0%' AND LENGTH(SETTLEMENT_ID) = 18;
DELETE FROM BLUEBERRY_CHAIN.RAW.CREDIT_NOTES;
DELETE FROM BLUEBERRY_CHAIN.RAW.LOT_COST_COMPONENTS
 WHERE SOURCE_TOOL <> 'SEED';

-- Restore Demo 1 lot to AVAILABLE
UPDATE BLUEBERRY_CHAIN.RAW.HARVEST_LOTS
   SET LOT_STATUS = 'AVAILABLE', HOLD_REASON = NULL,
       LAST_UPDATED_TS = CURRENT_TIMESTAMP()
 WHERE LOT_ID IN (
   'LOT-' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') || '-14-07',
   'LOT-' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') || '-14-05',
   'LOT-' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') || '-09-07',
   'LOT-' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') || '-06-06');

-- Restore shipment routing and status
UPDATE BLUEBERRY_CHAIN.RAW.SHIPMENTS
   SET STATUS = CASE WHEN ACTUAL_ARRIVAL_TS IS NOT NULL THEN 'ARRIVED'
                     ELSE 'IN_TRANSIT' END
 WHERE STATUS = 'DIVERTED';

-- Reset inventory holds except the two seeded quality holds
UPDATE BLUEBERRY_CHAIN.RAW.INVENTORY i
   SET HOLD_KG = 0, LAST_UPDATED_TS = CURRENT_TIMESTAMP()
 WHERE NOT EXISTS (
   SELECT 1 FROM BLUEBERRY_CHAIN.RAW.HARVEST_LOTS l
    WHERE l.LOT_ID = i.LOT_ID AND l.LOT_STATUS = 'HOLD');

-- Reset PO promise state (incl. Costco PO-6001)
UPDATE BLUEBERRY_CHAIN.RAW.RETAILER_POS
   SET PROMISE_CONFIDENCE_PCT = 100, STATUS = 'OPEN',
       LAST_UPDATED_TS = CURRENT_TIMESTAMP()
 WHERE PO_ID IN ('PO-5001','PO-5002','PO-5003','PO-6001');

UPDATE BLUEBERRY_CHAIN.RAW.PO_LINES
   SET FILL_STATUS = 'PENDING' WHERE PO_LINE_ID = 'POL-6001-1';
UPDATE BLUEBERRY_CHAIN.RAW.PO_LINES
   SET FILL_STATUS = 'FILLED'  WHERE PO_LINE_ID = 'POL-6001-2';

UPDATE BLUEBERRY_CHAIN.RAW.PO_LINES
   SET FILL_STATUS = 'PENDING' WHERE PO_LINE_ID = 'POL-5001-1';
UPDATE BLUEBERRY_CHAIN.RAW.PO_LINES
   SET FILL_STATUS = 'FILLED'  WHERE PO_LINE_ID = 'POL-5001-2';
UPDATE BLUEBERRY_CHAIN.RAW.PO_LINES
   SET FILL_STATUS = 'SHORT'   WHERE PO_LINE_ID = 'POL-5002-1';

-- ---------------------------------------------------------------------
-- Confirm the pinned scenarios are intact
-- ---------------------------------------------------------------------
SELECT 'DEMO 1 - hero lot' AS SCENARIO, LOT_ID, LOT_STATUS,
       ROUND(EXCURSION_HOURS, 2) AS EXCURSION_HOURS
FROM BLUEBERRY_CHAIN.CURATED.DT_HARVEST_LOT_CURRENT
WHERE LOT_ID = 'LOT-' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') || '-14-07';

SELECT 'DEMO 2 - Tracy arrivals uninvoiced' AS SCENARIO, COUNT(*) AS SHIPMENTS
FROM BLUEBERRY_CHAIN.RAW.SHIPMENTS s
WHERE s.DC_CODE = 'TRACY-DC'
  AND s.ACTUAL_ARRIVAL_TS::DATE = DATEADD('day', -1, CURRENT_DATE())
  AND NOT EXISTS (SELECT 1 FROM BLUEBERRY_CHAIN.RAW.INVOICES i
                   WHERE i.SHIPMENT_ID = s.SHIPMENT_ID);

SELECT 'RESET COMPLETE' AS STATUS;
